// priority: 0

// Visit the wiki for more info - https://kubejs.com/

console.info('Hello, World! (Loaded server scripts)')


ServerEvents.recipes((event) => {
    event.replaceOutput({ id: 'gtceu:neutron_activator/naquadria' }, Item.of('gtceu:naquadria_sulfate_dust', 3), Item.of('gtceu:naquadria_sulfate_dust', 9))
    event.replaceOutput({ id: 'gtceu:chemical_plant/enriched_naquadah_residue_solution' }, Fluid.of('gtceu:enriched_naquadah_residue_solution', 1000), Fluid.of('gtceu:enriched_naquadah_residue_solution', 2000))
    // event.remove({ id: 'gtceu:dehydrator/xenoauric_fluoroantimonic_acid' })
    event.recipes.gtceu.centrifuge('test')
        .inputFluids(Fluid.of('gtceu:naquadria_waste', 19000))
        .itemOutputs('58x gtceu:antimony_trifluoride_dust')
        .itemOutputs(Item.of('gtceu:gallium_sulfide_dust', 38))
        .outputFluids(Fluid.of('gtceu:fluorine', 32000))
        .outputFluids(Fluid.of('water', 100000))
        .outputFluids(Fluid.of('gtceu:oxygen', 44000))
        .outputFluids(Fluid.of('gtceu:sulfuric_acid', 86500))
        .outputFluids(Fluid.of('gtceu:hexafluoride_enriched_naquadah_solution', 2000))
        .EUt(5)
        .duration(5)
    event.remove({ id: 'gtceu:dehydrator/naquadria_waste' })
    event.remove({ id: 'gtceu:distillation_tower/naquadria_waste_separation' })
    event.remove({ id: 'gtceu:distillery/naquadria_waste_separation_to_enriched_naquadah_solution' })
    event.remove({ id: 'gtceu:distillery/naquadria_waste_separation_to_naquadria_solution' })
    event.remove({ id: 'gtceu:distillery/naquadria_waste_separation_to_sulfuric_acid' })
    event.replaceOutput({ id: 'gtceu:electrolyzer/xenoauric_fluoroantimonic_acid' }, Item.of('gtceu:antimony_trifluoride_dust', 1), Item.of('gtceu:antimony_trifluoride_dust', 4))
    event.recipes.gtceu.vacuum_freezer('helium_haft')
        .inputFluids(Fluid.of('gtceu:helium', 500))
        .EUt(1920)
        .duration(120)
        .outputFluids(Fluid.of('gtceu:liquid_helium', 500))
    event.recipes.gtceu.assembly_line('scanner_test2')
        .itemInputs("64x gtceu:titanium_ingot")
        .itemInputs('19x gtceu:indium_dust')
        .itemInputs('19x gtceu:phosphorus_dust')
        .itemInputs('50x gtceu:trinium_ingot')
        .itemInputs('45x gtceu:enriched_naquadah_ingot')
        .itemInputs('38x gtceu:naquadria_ingot')
        .itemInputs('38x gtceu:gallium_dust')
        .itemOutputs(Item.of('kubejs:token', 1))
        .inputFluids(Fluid.of('gtceu:helium', 30250))
        .inputFluids(Fluid.of('gtceu:enriched_naquadah_solution', 4000))
        .duration(240)
        .EUt(282624)
    event.recipes.gtceu
        .centrifuge("separate")
        .itemInputs(Item.of('kubejs:token', 3))
        .itemOutputs("522x gtceu:naquadah_dust")
        .itemOutputs("105x gtceu:rutile_dust")
        .outputFluids(Fluid.of('gtceu:liquid_helium', 181500))
        .duration(2400).itemOutputs(Item.of('gtnn:palladium_on_carbon_catalyst', 6))
        .EUt(32768);
})