// priority: 0

// Visit the wiki for more info - https://kubejs.com/

console.info('Hello, World! (Loaded server scripts)')


ServerEvents.recipes((event) => {
    event.replaceOutput({ id: 'gtceu:neutron_activator/naquadria' }, Item.of('gtceu:naquadria_sulfate_dust', 3), Item.of('gtceu:naquadria_sulfate_dust', 9))
    event.replaceOutput({ id: 'gtceu:chemical_plant/enriched_naquadah_residue_solution' }, Fluid.of('gtceu:enriched_naquadah_residue_solution', 1000), Fluid.of('gtceu:enriched_naquadah_residue_solution', 2000))
    // event.remove({ id: 'gtceu:dehydrator/xenoauric_fluoroantimonic_acid' })
    event.recipes.gtceu.centrifuge('test')
        .inputFluids(Fluid.of('gtceu:naquadria_waste', 19000))
        .itemOutputs('58x gtceu:antimony_trifluoride_dust')
        .itemOutputs(Item.of('gtceu:gallium_sulfide_dust', 38))
        .outputFluids(Fluid.of('gtceu:fluorine', 500))
        .outputFluids(Fluid.of('water', 100000))
        .outputFluids(Fluid.of('gtceu:oxygen', 44000))
        .outputFluids(Fluid.of('gtceu:sulfuric_acid', 124500))
        .outputFluids(Fluid.of('gtceu:impure_enriched_naquadah_solution', 2000))
        .EUt(5)
        .duration(5)
    event.remove({ id: 'gtceu:dehydrator/naquadria_waste' })
    event.remove({ id: 'gtceu:distillation_tower/naquadria_waste_separation' })
    event.remove({ id: 'gtceu:distillery/naquadria_waste_separation_to_enriched_naquadah_solution' })
    event.remove({ id: 'gtceu:distillery/naquadria_waste_separation_to_naquadria_solution' })
    event.remove({ id: 'gtceu:distillery/naquadria_waste_separation_to_sulfuric_acid' })
    event.replaceOutput({ id: 'gtceu:electrolyzer/xenoauric_fluoroantimonic_acid' }, Item.of('gtceu:antimony_trifluoride_dust', 1), Item.of('gtceu:antimony_trifluoride_dust', 4))
    // event.recipes.gtceu.vacuum_freezer('helium_haft')
    //     .inputFluids(Fluid.of('gtceu:helium', 500))
    //     .EUt(1920)
    //     .duration(120)
    //     .outputFluids(Fluid.of('gtceu:liquid_helium', 500))
    event.recipes.gtceu.assembly_line('scanner_test2')
        .itemInputs("61x gtceu:titanium_ingot")
        .itemInputs('19x gtceu:indium_dust')
        .itemInputs('19x gtceu:phosphorus_dust')
        .itemInputs('50x gtceu:trinium_ingot')
        .itemInputs('45x gtceu:enriched_naquadah_ingot')
        .itemInputs('38x gtceu:naquadria_ingot')
        .itemInputs('38x gtceu:gallium_dust')
        .itemInputs(Item.of('gtceu:potassium_dust',64))
        .itemOutputs(Item.of('kubejs:token', 1))
        .inputFluids(Fluid.of('gtceu:helium', 33250))
        .inputFluids(Fluid.of('gtceu:chlorine',64000))
        .inputFluids(Fluid.of('gtceu:enriched_naquadah_solution', 4000))
        .duration(240)
        .EUt(282624)
    event.recipes.gtceu
        .centrifuge("separate")
        .itemInputs(Item.of('kubejs:token', 3))
        .itemOutputs("522x gtceu:naquadah_dust")
        .itemOutputs("96x gtceu:rutile_dust")
        .outputFluids(Fluid.of('gtceu:helium', 199500))
        .duration(2400)
        // .itemOutputs(Item.of('gtnn:palladium_on_carbon_catalyst', 6))
        .itemOutputs(Item.of('gtceu:palladium_dust',6))
        .itemOutputs(Item.of('gtceu:carbon_dust',6))
        .itemOutputs(Item.of('gtceu:rock_salt_dust',384))
        .EUt(32768);
    event.recipes.gtceu.centrifuge('test_sulfur')
        .EUt(5)
        .duration(5)
        .inputFluids(Fluid.of('gtceu:sulfur_dioxide', 1000))
        .outputFluids(Fluid.of('gtceu:sulfur_dioxide', 1000))
        .itemOutputs(Item.of('kubejs:debug2'))
    event.recipes.gtceu.centrifuge('test_hex')
        .EUt(5)
        .duration(5)
        .inputFluids(Fluid.of('gtceu:hexafluoride_enriched_naquadah_solution', 1000))
        .outputFluids(Fluid.of('gtceu:hexafluoride_enriched_naquadah_solution', 1000))
        .itemOutputs(Item.of('kubejs:debug3'))
    event.recipes.gtceu.centrifuge('test_hf').EUt(5)
        .duration(5)
        .inputFluids(Fluid.of('gtceu:hydrofluoric_acid', 11000))
        .outputFluids(Fluid.of('gtceu:hydrofluoric_acid', 11000))
        .itemOutputs(Item.of('kubejs:debug4'))
    event.recipes.gtceu.distillation_tower('sep_hf')
        .EUt(1)
        .duration(1)
        .inputFluids(Fluid.of('gtceu:hydrofluoric_acid', 200))
        .outputFluids(Fluid.of('gtceu:hydrofluoric_acid', 129))
        .outputFluids(Fluid.of('gtceu:hydrofluoric_acid', 71))
        .disableDistilleryRecipes(true)
    event.recipes.gtceu.fluid_solidifier('test8')
        .inputFluids(Fluid.of('gtceu:potassium', 144))
        .notConsumable('gtceu:ingot_casting_mold')
        .itemOutputs('kubejs:potassium_ingot')
        .EUt(7)
        .duration(20)
    event.recipes.gtceu.macerator('test9')
        .itemInputs('kubejs:potassium_ingot')
        .itemOutputs('gtceu:potassium_dust')
        .duration(39)
        .EUt(4)
    event.remove({ id: 'gtec:large_chemical_reactor/potassium_disulfate' })
    event.recipes.gtceu.large_chemical_reactor('test5')
        .itemInputs('gtceu:sodium_dust')
        .inputFluids("minecraft:water 1000")
        .circuit(1)
        .itemOutputs('3x gtceu:sodium_hydroxide_dust')
        .outputFluids("gtceu:hydrogen 1000")
        .duration(200)
        .EUt(32)
    event.recipes.gtceu.large_chemical_reactor('test6')
        .inputFluids(Fluid.of('gtceu:hydrogen', 2000))
        .itemInputs('7x gtceu:sodium_sulfate_dust')
        .itemOutputs('2x gtceu:sodium_dust')
        .outputFluids('gtceu:sulfuric_acid 1000')
        .duration(30)
        .EUt(19)
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_rock_salt' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_potassium_hydroxide' })
    event.remove({ id: 'gtceu:large_chemical_reactor/potassium_carbonate' })
    event.remove({ id: 'gtceu:chemical_reactor/potassium_carbonate' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_potassium_carbonate' })
    event.remove({ id: 'gtceu:chemical_reactor/potassium_cyanide' })
    event.replaceOutput({ id: 'gtceu:large_chemical_reactor/potassium_cyanide' }, Fluid.of('minecraft:water', 1000), Fluid.of('minecraft:water', 2000))
    event.remove({ id: 'gtceu:fluid_heater/formamide' })
    event.recipes.gtceu.distillation_tower('formamide')
        .disableDistilleryRecipes(true)
        .inputFluids(Fluid.of("gtceu:ammonium_formate", 100))
        .outputFluids(Fluid.of("gtceu:formamide", 100))
        .outputFluids(Fluid.of("minecraft:water", 100))
        .EUt(24).duration(20)


})