
[infernal_boiler]
	#Range: 0.1 ~ 100.0
	basicSupremeCoef = 2.0
	#Range: 0.1 ~ 100.0
	coilSupremeCoef = 0.5

[industrial_gas_pressurizer]
	#Range: 0.0 ~ 5.0
	percentageIncrease = 0.25
	#Range: 0.01 ~ 1.0
	lowerThreshold = 0.35
	#Range: 0.01 ~ 1.0
	upperThreshold = 0.85

